# Generated by Django 4.2.30 on 2026-07-21 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='parent',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'Parent'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='users.profile'),
        ),
    ]
