# Generated by Django 4.2.30 on 2026-07-22 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='parent',
        ),
    ]
