# Generated by Django 4.2.30 on 2026-07-22 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
