# Generated by Django 4.2.30 on 2026-07-22 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0003_course_teacher_email_course_teacher_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='teacher_email',
        ),
        migrations.RemoveField(
            model_name='course',
            name='teacher_name',
        ),
        migrations.RemoveField(
            model_name='course',
            name='teacher_phone',
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'profile__role': 'Teacher'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
